### ISSUE TITLE
Alignment error when displaying "THIS PRODUCT HAS BEEN DISCONTINUED"

### ISSUE THREAD

**Issue by dan201uk** [twoelevenjay/woocommerce-discontinued-products#2]
Screen shot.
Wordpress: 4.5.3
Woocommerce : 2.6.4
Theme: WooPress 2.9.2

![error](https://cloud.githubusercontent.com/assets/22027339/18272703/2d53d0b2-7431-11e6-8de1-0962f39066d5.png)

I have done a temporary fix by adding &NBSP<div> </div> Which fixes the problem, but means i have modified a plugin file.

**Comment by twoelevenjay** [comment]
Thank you for reporting this? May I have the URL to this page? I imagine the plugin generated HTML, is not integrating with the themes HTML well. I would like to take a closer look. It is ok that it has the temporary fix while I look.

**Comment by dan201uk** [comment]
Thank you for come back so quickly. [http://www.inds.co.uk/product/fd8612dpt25r8az-differential-pressure-transmitter/](url)
