### ISSUE TITLE
Strings missing in translation

### ISSUE THREAD

**Issue by tobiasgardner** [twoelevenjay/woocommerce-discontinued-products#4]
The following seems to be missing in the translation file:
- Discontinued page
- (Help text related to the above field)

**Comment by twoelevenjay** [comment]
Thank you for pointing this out. I have updated the .pot file.

https://github.com/twoelevenjay/woocommerce-discontinued-products/commit/afb5f4c22a209e2acc62a3e20ed3348428f98080
